### PR TITLE
V3 : Breaking change - Big Upgrade

### PR DESCRIPTION
**Pull request by Zakarialabib**
After seen huge traffic those past months, i decided lately to get back to maintenance and upgrading the most loved project .

this commit will cover upgrading the project from older version to laravel 11 and livewire 3 .
as well as removing and upgrading methods, making less and better code.

im preparing my library of components mainly on livewire volt , i will be playing and making from what ive coded until now. 

feel free to discuss the ways we could make this project adapt to every management architecture mainly Business.

Thank you for testing and giving your feedback

### CODE REVIEW

**Comment by mostafa-amine** [comment]
Hi Zakaria, cool idea 
However the project should require `pestphp/pest` in order to run tests.

**Comment by mostafa-amine** [comment]
I have noticed some bugs and i have the ability to fix them, should i create a new PR from this branch or?

**Comment by Zakarialabib** [comment]
> I have noticed some bugs and i have the ability to fix them, should i create a new PR from this branch or? 

Yes sure , im still working on upgrading the project in several aspects , but ur help will be greaat . Thanx.

Copy v3 upgrade branch work on it open a pr and let me review it

**Comment by Zakarialabib** [comment]
> Hi Zakaria, cool idea 
> However the project should require `pestphp/pest` in order to run tests.

Test was installed but all test built were not yet fix based on changes made lately.

**Pull request merged**
