### PR TITLE
Backup & logs

### PR DESCRIPTION
**Pull request by Zakarialabib**

### CODE REVIEW

**Comment by ismaail** [comment]
you don't need to implement this yourself,

You can use [spatie/laravel-backup](https://github.com/spatie/laravel-backup) package to save project files & the database to a remote ftp server.

**Comment by Zakarialabib** [comment]
@ismaail spatie already exists in the project, it's the best option available, i wanted to compare & make some controllable mecanics for backup, iwrote something about that under project tab.

**Comment by ismaail** [comment]
@Zakarialabib if you want to make a backup from the controller, 

all you have to do is call the backup command with `Artisan::call`

```php
use Illuminate\Support\Facades\Artisan;

Artisan::call('backup:run')
```

**Comment by Zakarialabib** [comment]
truee, i will try to change that

**Pull request merged**
